# Generated by Django 4.2.11 on 2024-03-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToDo_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
