# Generated by Django 4.2.11 on 2024-03-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0007_alter_todo_due_date_day_alter_todo_due_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date_day',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date_time',
        ),
    ]
