# Generated by Django 4.2.11 on 2024-03-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0010_todo_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
    ]
