# Generated by Django 4.2.11 on 2024-03-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0015_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
