# Generated by Django 4.2.11 on 2024-03-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0019_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
